spring:
  datasource:
    url: jdbc:mysql://192.168.118.3:3306/gulimall_sms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis-plus:
  global-config:
    db-config:
      id-type: auto